# Generated by Django 4.1 on 2023-09-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_counties',
            new_name='published_countries',
        ),
    ]
